Repository Agility-Creative-Solutions/scrummy-app, pull requests merged in 2022-12, with the labels that each got.

#10 feat: improve buttons and colors
  src/components/atoms/Button/index.tsx
  src/components/atoms/Loader/index.tsx
  src/pages/design-system.tsx
  src/pages/index.tsx
  tailwind.config.js
Labels: enhancement

#9 feat: add framer motion and card component
  package.json
  src/components/atoms/Card/StyledCard.tsx
  src/components/atoms/Card/index.tsx
  src/components/atoms/Modal/Backdrop.tsx
  src/components/atoms/Modal/index.tsx
  src/pages/design-system.tsx
  yarn.lock
Labels: wip, do not merge

#13 EPIC: Checkbox, RadioButton & IconButton
  package-lock.json
  src/components/atoms/Button/index.tsx
  src/components/atoms/CheckBox/index.tsx
  src/components/atoms/Icon/index.tsx
  src/components/atoms/IconButton/index.tsx
  src/components/atoms/Input/index.tsx
  src/components/atoms/ProgressBar/index.tsx
  src/components/atoms/RadioButton/index.tsx
  src/components/atoms/index.ts
  src/hooks/useMdIcons.tsx
  src/pages/design-system.tsx
Labels: enhancement, wip
